version = 0.1

[default.deploy.parameters]
stack_name = "resume-stack"
resolve_s3 = true
s3_prefix = "resume-stack"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ProjectName=\"abishek-resume\""
image_repositories = []
